// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYGIMnjnGwbIjwN00utOLo5HKebl_27o',
    appId: '1:35521851237:web:1d85ea104c5f042dd1fb8c',
    messagingSenderId: '35521851237',
    projectId: 'mynotes-f7ffc',
    authDomain: 'mynotes-f7ffc.firebaseapp.com',
    storageBucket: 'mynotes-f7ffc.appspot.com',
    measurementId: 'G-Q6V1EZL20M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxyhPs-doW0xB6j-FMTl7KE5E_0T4vUQ',
    appId: '1:35521851237:android:39ed8773c3a59b48d1fb8c',
    messagingSenderId: '35521851237',
    projectId: 'mynotes-f7ffc',
    storageBucket: 'mynotes-f7ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0t4frQqgcmDGQ41Cdp4Er3RccEweiQTM',
    appId: '1:35521851237:ios:054b69fdf35c1b3ad1fb8c',
    messagingSenderId: '35521851237',
    projectId: 'mynotes-f7ffc',
    storageBucket: 'mynotes-f7ffc.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0t4frQqgcmDGQ41Cdp4Er3RccEweiQTM',
    appId: '1:35521851237:ios:054b69fdf35c1b3ad1fb8c',
    messagingSenderId: '35521851237',
    projectId: 'mynotes-f7ffc',
    storageBucket: 'mynotes-f7ffc.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );
}
